### ISSUE TITLE
Search broken by OTP 27 update of docs

### ISSUE THREAD

**Issue by jrfondren** [erlang/erlang-org#138]
## replication

1. go https://www.erlang.org/
2. click on 'Documentation' link at top, to https://www.erlang.org/docs
3. click 'Erlang/OTP Documentation' link at top, to https://www.erlang.org/doc/
4. click in the search box at the top
5. type 'unicode' and hit enter
6. result: a broken page from Erlang/OTP 24.1.4, at https://www.erlang.org/doc/search.html?v=27&q=unicode

![searchresult](https://github.com/erlang/erlang-org/assets/41455523/5b2146e3-64f6-4eab-a8cc-d696f860da92)

**Comment by garazdawi** [comment]
Thanks for the report! The CSS links had not been updated. Fixed in master, will be published online soon.
