### ISSUE TITLE
Edit links from the searchable doc page do not work

### ISSUE THREAD

**Issue by robertoaloi** [erlang/erlang-org#14]
When hovering a function names in the searchable docs (i.e. the docs at http://erlang.org/doc/search/), a pencil button shows up. Clicking on the pencil should bring to the GitHub page where the code for that doc is defined. Instead, an empty page is shown.

E.g.  -> Modules -> Array -> fix/1

This works correctly in the docs without the search functionality.

**Comment by garazdawi** [comment]
I'm guessing that github does not allow itself to be embedded in a frame. If you middle-click you get to the place you want.

So I guess we have to do the same thing and detect if we are in a frame and then open github in a new tab or outside the frame.

**Comment by robertoaloi** [comment]
Looking at the Chrome console:

```
Refused to display 'https://github.com/erlang/otp/edit/maint/lib/stdlib/doc/src/array.xml#L148' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
```

**Comment by robertoaloi** [comment]
I think opening the link in a new tab is perfectly fine. After all, you may want to continue reading the docs and editing the docs from the browser is not an extremely common use case. So, I would personally not even make that distinction but always open those links in a new tab.

**Comment by garazdawi** [comment]
I like having the option to choose whether I want it in a new tab, new window or the same tab, which is why I did it the way it is. But if it breaks when using the search docs it may be a good idea to change it.

**Comment by garazdawi** [comment]
This issue is solved with the launch of the new website.
