### ISSUE TITLE
Add .html to redirects

### ISSUE THREAD

**Issue by wojtekmach** [erlang/erlang-org#142]
Going to <https://www.erlang.org/doc/man/zlib> redirects to <https://www.erlang.org/doc/apps/erts/zlib> however notice "zlib" is not "selected" in the sidebar:

<img width="1510" alt="image" src="https://github.com/erlang/erlang-org/assets/76071/2d8f61ee-2246-40b1-9d2e-4992c8e65e00">

only when we click it in the sidebar it is:

<img width="1510" alt="image" src="https://github.com/erlang/erlang-org/assets/76071/de43e8f0-596d-4a13-bd56-17e9372d7759">

and the difference is:

* <https://www.erlang.org/doc/apps/erts/zlib>
* <https://www.erlang.org/doc/apps/erts/zlib.html>

This makes a big difference in apps with lots of modules like stdlib:

* <https://www.erlang.org/doc/apps/stdlib/gen_server>
* <https://www.erlang.org/doc/apps/stdlib/gen_server.html>

In the latter case, ExDoc highlights the module name and importantly scrolls sidebar down to its position.

If possible, I believe a quick fix is to add .html extension to redirects. Otherwise, we can look into support it in ExDoc somehow.

**Comment by garazdawi** [comment]
On netlify all URLs can be given without the `.html` extension, so even if we fix the redirects, google search and others can crawl to the variant without `.html` extension. So I think this problem needs to be solved in ex_doc.

**Comment by wojtekmach** [comment]
Got it, thanks, I'll look into it.

**Comment by wojtekmach** [comment]
If it would not break anything (and be even possible, no idea) would you be open to „un-prettify” links on Netlify, that is, non-.html urls would redirect to with .html? The benefits would be possible better SEO, instead of having both /gen_server and /gen_server.html links out there we’d standardize on the latter which would match ExDoc generated ones using autolinking feature.

**Comment by josevalim** [comment]
For now, I have fixed ExDoc to handle URLs without .html, there were three spots, but there are probably more. We could also setup a redirect on ExDoc side though.

Regarding better SEO, I recommend Erlang to set the --canonical flag/config. This way, Erlang can keep a history of OTP versions hosted, but Google will only redirect to the main, latest one. This will solve both the .html issue AND any versioning. Here is where we set canonical in Elixir, we set it for everything, except for nightly/main builds: https://github.com/elixir-lang/elixir/blob/f0ebedc627220fef490ea2382432332d2d250466/lib/elixir/scripts/mix_docs.exs#L6

PS: if there are any questions if all versions should point to the latest one as canonical, this seems to have been the consensus in the Elixir community. People were getting frustrating from Elixir v1.12 being the top results while 1.16 was out (and so on).

**Comment by garazdawi** [comment]
I've opened #143 to address some issues. I don't think I can make Netlify redirect all URLs without .html to the .html version, but I can look into it.

**Comment by josevalim** [comment]
@garazdawi we could also set the redirect by injecting some JS code in `<head>` but perhaps canonical is enough.

**Comment by garazdawi** [comment]
Closing this for now. Please let me know if you encounter any more issues.
