### ISSUE TITLE
Outdated information for "Erlang Tools"

### ISSUE THREAD

**Issue by robertoaloi** [erlang/erlang-org#146]
The page at https://www.erlang.org/faq/tools contains a number of outdated information.

* Formatter -> Could point to erlfmt and other formatters
* Benchmark -> Outdated
* IDEs -> Does not include any language server such as Erlang LS or ELP
* Refactoring -> Does not mention Wrangler, RefactorErl or ELP
* Static Analysis -> Does not mention Eqwalizer and friends

I could not find the source for the page either in this repo or in the erlang/otp one. Could someone please point me to the source and/or update the page?

**Comment by garazdawi** [comment]
At per the [README.md](https://github.com/erlang/erlang-org?tab=readme-ov-file#faq) in this project, it is located here: https://github.com/matthiasl/Erlang-FAQ.

**Comment by robertoaloi** [comment]
Ops, totally missed that. The repo feels very much outdated. Last update is from 2 years ago. Maybe we should just kill it and replace the FAQ with a page in this very same repo?

**Comment by garazdawi** [comment]
Yes, that seems reasonable.
