### ISSUE TITLE
Sidebar missing until mermaidjs finishes loading

### ISSUE THREAD

**Issue by vlad-ngn** [erlang/erlang-org#150]
Hi!

Screenshot 1:
Sidebar missing, **mermaidjs** loading

![Screenshot from 2024-08-05 15-59-31](https://github.com/user-attachments/assets/3d531d0a-6966-4818-93e4-ba6e332717a1)

Screenshot 2:

Sidebar appeared after **mermaidjs** loaded

![Screenshot from 2024-08-05 15-59-54](https://github.com/user-attachments/assets/3f40d964-0127-4ada-b12c-b46aa9b614e8)

This is a problem for me, because **mermaidjs** takes ~ 1 minute to load.
Problem appeared after website update recently.

Browser: 
Google Chrome
Version 126.0.6478.126 (Official Build) (64-bit)

**Comment by garazdawi** [comment]
This was done as part of https://github.com/erlang/otp/pull/8197. Maybe @Benjamin-Philip has some idea about how it can be improved?

**Comment by Benjamin-Philip** [comment]
Hi @vlad-ngn , can you replicate the issue with Elixir's GenServer docs?

The mermaid setup in Erlang was more or else copied as is from Elixir's. It's very likely that this issue affects Elixir's docs too.

**Comment by vlad-ngn** [comment]
> Hi @vlad-ngn , can you replicate the issue with Elixir's GenServer docs?
> 
> The mermaid setup in Erlang was more or else copied as is from Elixir's. It's very likely that this issue affects Elixir's docs too.

Yes, same issue with Elixir's docs

<details>
  <summary>Screenshots</summary>

![Screenshot from 2024-08-12 18-28-14](https://github.com/user-attachments/assets/0100366f-179a-401c-8d2e-f03b9f831df5)
![Screenshot from 2024-08-12 18-28-45](https://github.com/user-attachments/assets/f4d95493-79bd-41d9-833b-33329f0517f4)

</details>

**Comment by Benjamin-Philip** [comment]
In that case, you should file an issue upstream in ExDoc or Elixir repo. Please tag me as well.

**Comment by vlad-ngn** [comment]
Thanks!
Created issue in the ExDoc repo: https://github.com/elixir-lang/ex_doc/issues/1941
