### ISSUE TITLE
Wrong file encoding in README files?

### ISSUE THREAD

**Issue by michallepicki** [erlang/erlang-org#160]
I followed a link from the latest release to https://erlang.org/download/OTP-27.2.README

Scrolling down to the end, I see wrong encoding in Firefox on Windows 11:
![image](https://github.com/user-attachments/assets/3e7be7d5-a45e-49c7-9604-0884e769dff0)

I think it may be an encoding issue (not sure at which step though, when these files are generated or served?) 🤔🤔

**Comment by garazdawi** [comment]
It is your webbrowser that is interpreting it as latin1 when it is utf8. Not sure what can be done about that. Any idea?

**Comment by michallepicki** [comment]
I also checked Edge, it behaves the same way, so maybe it's a bad default by Windows for my system language? 🤔

Maybe setting
```
    charset utf-8;
```
in the correct location in nginx config, so that it specifies the encoding in the `Content-Type` response header would fix this

**Comment by garazdawi** [comment]
Should be fixed now.
