### ISSUE TITLE
Menu not working on Android phones 

### ISSUE THREAD

**Issue by crownedgrouse** [erlang/erlang-org#2]
https://bugs.erlang.org/browse/ERL-125

**Comment by crownedgrouse** [comment]
Any chance this to be fixed one day?

**Comment by crownedgrouse** [comment]
Is somebody maintaining this site? Issue still there.

**Comment by KennethL** [comment]
Yes, we are maintaining the site. Does the menu work on iPhone?
I also discovered the problem with Android, we will try to fix it.

Kenneth,  Erlang/OTP, Ericsson

**Comment by crownedgrouse** [comment]
Thanks Kenneth,
unfortunately I'm not an Apple user and do not have right now access to an iPhone.
I will check with some colleague's phone.

**Comment by garazdawi** [comment]
It is most likely because the bootstrap.min.js file in https://github.com/erlang/erlang-org/blob/master/templates/assets.dtl will not load as the sha384 has changed for some reason... trying to figure out why it may have changed and if it matters.

**Comment by garazdawi** [comment]
Solved but not yet deployed.

**Comment by garazdawi** [comment]
Deployed

**Comment by crownedgrouse** [comment]
"Alive... It's alive !!!!"
Great. Working well . Thanks !
