### ISSUE TITLE
Broken deep-links

### ISSUE THREAD

**Issue by Maria-12648430** [erlang/erlang-org#33]
With the release of the new erlang.org (congrats, btw, it looks great 😍), some deep links got broken, including ones in the blog posts on the site itself. For example, try the link titled "EEP 48" here: https://www.erlang.org/blog/my-otp-24-highlights/#eep-48-documentation-chunks-for-edoc

**Comment by garazdawi** [comment]
Should be fixed now. Thanks for reporting!
