### ISSUE TITLE
Add instantSearch for url based search queries

### ISSUE THREAD

**Issue by starbelly** [erlang/erlang-org#35]
After switching to the static site an issue some pointed out was the inability to search via url query parameters (i.e., `https://erlang.org/?q=eh`. 

Did some quick research around agolia search and found this is possible using instantSearch, which I also observed people using in along side  docsearch. 

A good example of this would be gitlab's doc site or docsearch's own site, both of which are static sites.  

 Examples : 

[https://docs.gitlab.com/search/?q=eh](https://docs.gitlab.com/search/?q=eh)

[https://docsearch.algolia.com/search/?q=url](https://docsearch.algolia.com/search/?q=url)

Some example code : 

[https://gitlab.com/gitlab-org/gitlab-docs/-/blob/main/content/frontend/search/index.js](https://gitlab.com/gitlab-org/gitlab-docs/-/blob/main/content/frontend/search/index.js)

[https://gitlab.com/gitlab-org/gitlab-docs/-/blob/main/layouts/instantsearch-head.html](https://gitlab.com/gitlab-org/gitlab-docs/-/blob/main/layouts/instantsearch-head.html)

[https://gitlab.com/gitlab-org/gitlab-docs/-/blob/main/layouts/instantsearch.html](https://gitlab.com/gitlab-org/gitlab-docs/-/blob/main/layouts/instantsearch.html)

As we can see, there's not much going on there. instantSearch and agoliasearch are doing all the work. 

Documentation for instantSearch routing : 

[https://community.algolia.com/instantsearch.js/v2/guides/routing.html](https://community.algolia.com/instantsearch.js/v2/guides/routing.html)

We'd optimally just use `/?q=` so that bookmarks people had previously would continue to work.

**Comment by starbelly** [comment]
@garazdawi Got a simple version of this working. Needs some tweaking, but  : 


<img width="978" alt="Screen Shot 2021-11-04 at 7 44 38 PM" src="https://user-images.githubusercontent.com/39971740/140439730-1d88541c-0c66-4f2b-a4bd-a1fe37361ca7.png">

More tweaking and styling to do. I'll open a PR soonish. 

We'll need to add a redirect to  `_redirects` file for `/doc?q=foo` such that it redirects to `/doc/search?q=foo` as documented here : https://docs.netlify.com/routing/redirects/redirect-options/#query-parameters

**Comment by garazdawi** [comment]
Great!

I've spent the day trying to make the search results as good as possible and while it is better than before it is far from perfect. Having the building blocks to use instantSearch would allow us to better direct what results we would want.

For example: searching for "fold" in when browsing the "lists" module we today search all of Erlang/OTP. But we could with a different front-end search only in the current module, current application, only reference manuals or only user's guides.
