### ISSUE TITLE
Modal search box snippet is misleading when searching for specific module:function

### ISSUE THREAD

**Issue by seriyps** [erlang/erlang-org#51]
When searching for a specific function, say, `erlang:self` via modal pop-up Ctrl+K the search results produced are actually relevant, but the search snippet shows quite misleading information, see the screenshot:

![image](https://user-images.githubusercontent.com/422014/141308801-cc4c5c82-489b-487a-8fba-20ae79220a9e.png)

While first result actually points to https://www.erlang.org/doc/man/erlang.html#self-0, the snippet does not make it clear and rather looks like some random match over some random function's documentation.

I think more appropriate solution would be to display at least `erlang:self()` in the snippet or even better - the typespec of this function. Or something more similar to how it looks on this page https://www.erlang.org/doc/search?q=erlang%3Aself

![image](https://user-images.githubusercontent.com/422014/141309296-a36e3f07-fb64-4f6e-ac26-79988e170aee.png)

**Comment by garazdawi** [comment]
It should be possible to get better info by supplying a custom [hitcomponent](https://docsearch.algolia.com/docs/api#hitcomponent) to the DocSearch widget.

Possibly it may also work by restructuring the search data, will have to dig a bit into how the DocSearch widget decides what to display when by default.

**Comment by garazdawi** [comment]
Opened #52 with an attempt to solve this. That looks better right?

**Comment by seriyps** [comment]
Yes, much better, thanks!
