### ISSUE TITLE
Unable to find the tar.gz package of the documentation

### ISSUE THREAD

**Issue by eksperimental** [erlang/erlang-org#54]
I spent a good amount of time looking for it to no avail.
Finally i found them in the release section of the GitHub repository. 
I think the links do download the links should be included with each release.

**Comment by garazdawi** [comment]
In #55 I've added dropdowns to access the download URLs to the documentation. Please have a look and see if it is what you had in mind.

**Comment by eksperimental** [comment]
It looks really good.
But it is kind of hidden, inside the "View documentation".
I think below VIEW DOCUMENTATION we could have DOWNLOAD DOCUMENTATION, and if you click on the button or on the arrow, it will show the drop´-down that we show now.
