### ISSUE TITLE
Reusing source code, question about the license

### ISSUE THREAD

**Issue by eksperimental** [erlang/erlang-org#60]
Hi,
I am releasing an Elixir app, which uses ported code from this project into Elixir,

https://github.com/erlang/erlang-org/blob/master/_scripts/src/

I would like to know which license is this released under, if Apache 2 or the Erlang Public License, to give the proper credits,
Thank you.

**Comment by garazdawi** [comment]
Everything is released under Apache 2. The EPLICENSE file is part of this repo because it is part of the website to show what the license is for code before we moved to Apache 2.

**Comment by eksperimental** [comment]
Thank you @garazdawi 
One file question, the copyright holder should be cited as the same in https://github.com/erlang/otp#license   ?

**Comment by garazdawi** [comment]
yes
