### ISSUE TITLE
Search page with no terms lists modules in reverse alphabetical order

### ISSUE THREAD

**Issue by eksperimental** [erlang/erlang-org#69]
https://www.erlang.org/doc/search

![image](https://user-images.githubusercontent.com/9133420/150190184-8f97c3a3-8034-4382-a376-c5700b7eef16.png)

**Comment by garazdawi** [comment]
I'll merge this issue into #50. I've tried to do something about this, but it is harder than one would think...

**Comment by eksperimental** [comment]
Ok. Thank you
