### ISSUE TITLE
Symantec certs are being distrusted.

### ISSUE THREAD

**Issue by DAlperin** [erlang/erlang-org#7]
Soon you will not be able to access the website over https from most major browsers without having to add a security exception. This issue can be solved by switching to a lets encrypt cert or something else.

**Comment by judge2020** [comment]
Breaks on current stable chrome:

![image](https://user-images.githubusercontent.com/8601934/41513762-0464acba-726f-11e8-8b1a-8f50940dab9f.png)

**Comment by RaimoNiskanen** [comment]
On Sun, Jun 17, 2018 at 05:43:00PM -0700, Hunter wrote:
> Breaks on current stable chrome:
> 
> ![image](https://user-images.githubusercontent.com/8601934/41513762-0464acba-726f-11e8-8b1a-8f50940dab9f.png)

Ok.  The certificates were to expire mid august, so I kind of hoped that
would come first...  Thank you for reporting this.


-- 

/ Raimo Niskanen, Erlang/OTP, Ericsson AB
