### ISSUE TITLE
Documentation downloads not available for 25.1

### ISSUE THREAD

**Issue by Kapeli** [erlang/erlang-org#94]
Hi. Documentation downloads seem to not be available for 25.1 at https://erlang.org/download/. The latest version available is [otp_doc_html_25.0.tar.gz](https://erlang.org/download/otp_doc_html_25.0.tar.gz). Could they be added?

**Comment by garazdawi** [comment]
Yes, they probably should. In the meantime, you can also download them from the github release: https://github.com/erlang/otp/releases/tag/OTP-25.1

**Comment by proxyles** [comment]
I will have a look on why it is missing
